apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minesweeper-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium  
  resources:
    requests:
      storage: 500Mi