# apiVersion: resources.azure.com/v1alpha1api20200601
# kind: ResourceGroup
# metadata:
#   name: wksp-rg
#   namespace: default
# spec:
#   location: eastus
---
apiVersion : v1
kind : Secret
metadata : 
  name : server-admin-pw
  namespace : default
data:
  password: aGFja2F0aG9uUGFzcw== # hackathonPass
type: Opaque

--- 
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServer
metadata:
  name: wksp-pqslserver
  namespace: default
spec:
  location: eastus
  owner:
    name: wksp-rg
  version: "13"
  sku:
    name: Standard_B1ms
    tier: Burstable
#    family: Gen5
#    size: "51200"
#    capacity: 2
  administratorLogin: myAdmin
  administratorLoginPassword: # This is the name/key of a Kubernetes secret in the same namespace
    name: server-admin-pw
    key: password
  storage:
    storageSizeGB: 32
--- 
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersConfiguration
metadata:
  name: pgaudit
  namespace: default
spec:
  owner:
    name: wksp-pqslserver
  azureName: pgaudit.log
  source: user-override
  value: READ
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersDatabase
metadata:
  name: wksp-db
  namespace: default
spec:
  owner:
    name: wksp-pqslserver
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersFirewallRules
metadata:
  name: wksp-fw-rule
  namespace: default
spec:
  owner:
    name: wksp-pqslserver
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255