apiVersion: resources.azure.com/v1alpha1api20200601
kind: ResourceGroup
metadata:
  name: user1-wksp-rg
  namespace: default
spec:
  location: {{ azure_region }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: server-admin-pw
  namespace: default
data:
  password: cjNkaDR0MSE= # hackathonPass
type: Opaque

--- 
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServer
metadata:
  name: user1-minesweeper-database
  namespace: default
spec:
  location: {{ azure_region }}
  owner:
    name: user1-wksp-rg
  version: "13"
  sku:
    name: Standard_B1ms
    tier: Burstable
#    family: Gen5
#    size: "51200"
#    capacity: 2
  administratorLogin: quarkus
  administratorLoginPassword: # This is the name/key of a Kubernetes secret in the same namespace
    name: server-admin-pw
    key: password
  storage:
    storageSizeGB: 32
--- 
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersConfiguration
metadata:
  name: pgaudit
  namespace: default
spec:
  owner:
    name: user1-minesweeper-database
  azureName: pgaudit.log
  source: user-override
  value: READ
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersDatabase
metadata:
  name: score
  namespace: default
spec:
  owner:
    name: user1-minesweeper-database
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersFirewallRule
metadata:
  name: user1-minesweeper-database-fw-rule
  namespace: default
spec:
  owner:
    name: user1-minesweeper-database
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255
