# apiVersion: resources.azure.com/v1alpha1api20200601
# kind: ResourceGroup
# metadata:
#   name: wksp-rg
#   namespace: default
# spec:
#   location: {{ azure_region }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: server-admin-pw1
  namespace: default
data:
  password: r3dh4t1!
type: Opaque

--- 
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServer
metadata:
  name: arohack-minesweeper1
  namespace: default
spec:
  location: {{ azure_region }}
  owner:
    name: arohack
  version: "13"
  sku:
    name: Standard_B1ms
    tier: Burstable
#    family: Gen5
#    size: "51200"
#    capacity: 2
  administratorLogin: quarkus
  administratorLoginPassword: # This is the name/key of a Kubernetes secret in the same namespace
    name: server-admin-pw1
    key: password
  storage:
    storageSizeGB: 32
--- 
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersConfiguration
metadata:
  name: pgaudit1
  namespace: default
spec:
  owner:
    name: arohack-minesweeper1
  azureName: pgaudit.log
  source: user-override
  value: READ
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersDatabase
metadata:
  name: score
  namespace: default
spec:
  owner:
    name: arohack-minesweeper1
  charset: utf8
---
apiVersion: dbforpostgresql.azure.com/v1beta20210601
kind: FlexibleServersFirewallRule
metadata:
  name: wksp-fw-rule1
  namespace: default
spec:
  owner:
    name: arohack-minesweeper1
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255
